framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus: ~
            query.bus: ~
            event.bus: ~

        transports:
            sync: 'sync://'
            async: 'in-memory://'
